# Generated by Django 5.1.5 on 2025-04-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='isbn',
        ),
    ]
